#!/usr/bin/env node
/**
 * sync-theme.mjs
 *
 * Reads the colour / motion tokens declared in src/config/theme.ts
 * and rewrites the marked block in src/styles/global.css so
 * Tailwind 4's `@theme` directive stays in sync without manual
 * copy-paste.
 *
 * Why a script and not a Vite plugin:
 *   - It mirrors the existing pattern (scripts/generate-og-image.mjs
 *     also runs in the `prebuild` hook). Two scripts, two responsibilities.
 *   - We don't need TypeScript at runtime: theme.ts is parsed as plain
 *     text with regexes targeting the exact known shape of the file.
 *     This avoids tsx/ts-node/require-style ESM evaluation, which is
 *     fragile in modern Node + Astro setups.
 *   - The script is idempotent. Running it twice produces the same
 *     output. Safe to call from prebuild and from a watcher if we ever
 *     want one.
 *
 * Markers in global.css:
 *   /* THEME_AUTOGEN_START *​/  ← single-line marker (no inner space)
 *   ... @theme block ...
 *   /* THEME_AUTOGEN_END *​/
 *
 * If the markers are missing, the script aborts loudly rather than
 * blindly modifying the file — keeping global.css's other custom
 * blocks safe.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = resolve(__dirname, '..');

const THEME_PATH = resolve(projectRoot, 'src/config/theme.ts');
const CSS_PATH = resolve(projectRoot, 'src/styles/global.css');

const START_MARKER = '/* THEME_AUTOGEN_START */';
const END_MARKER = '/* THEME_AUTOGEN_END */';

/**
 * Pull a string-literal value out of a TS object snippet by the key.
 * Works for the `colors` / `fonts` / `motion` blocks because each
 * value is a plain string literal (single, double or backtick).
 */
function pickValue(blockText, key) {
	const re = new RegExp(`${key}\\s*:\\s*(['"\`])([\\s\\S]*?)\\1`, 'm');
	const match = blockText.match(re);
	if (!match) {
		throw new Error(
			`sync-theme: could not find key "${key}" in theme.ts. ` +
				'Did the file shape change?',
		);
	}
	return match[2];
}

function extractBlock(source, blockName) {
	// Match `<blockName>: { ... }` non-greedily until the matching brace.
	// Theme blocks are flat (no nested braces), so a simple match works.
	const re = new RegExp(`${blockName}\\s*:\\s*\\{([^}]*)\\}`, 'm');
	const match = source.match(re);
	if (!match) {
		throw new Error(
			`sync-theme: could not find block "${blockName}" in theme.ts.`,
		);
	}
	return match[1];
}

function generateThemeBlock(theme) {
	return `${START_MARKER}
@theme {
\t/* AUTOGENERATED from src/config/theme.ts by scripts/sync-theme.mjs.
\t   Do NOT edit by hand — your edits will be overwritten on the next
\t   build. To change tokens, edit theme.ts and re-run \`pnpm build\`
\t   (or \`pnpm dev\` will pick up the change on the next prebuild). */

\t/* Typography — values come from astro.config.mjs Fonts API which
\t   sets these as CSS vars on the document root; we declare them on
\t   @theme so Tailwind utilities like \`font-display\` / \`font-body\`
\t   are generated.
\t   Monospace stays on the system stack (no bundled web mono). */
\t--font-display: var(--font-playfair-display-sc), Georgia, serif;
\t--font-body: var(--font-karla), system-ui, sans-serif;
\t--font-mono: ui-monospace, SFMono-Regular, Menlo, monospace;

\t/* Semantic colours — warm paper shell + vivid orange accent (logo-aligned). */
\t--color-background: ${theme.colors.background};
\t--color-foreground: ${theme.colors.foreground};
\t--color-muted: ${theme.colors.muted};
\t--color-border: ${theme.colors.border};
\t--color-card: ${theme.colors.backgroundAlt};
\t--color-primary: ${theme.colors.primary};
\t--color-primary-foreground: ${theme.colors.primaryForeground};

\t/* Secondary accent — deeper burnt-orange surfaces; CTAs stay on \`primary\`.
\t   Components opt-in via \`bg-accent\` / \`text-accent\`. */
\t--color-accent: ${theme.colors.accent};
\t--color-accent-hover: ${theme.colors.accentHover};
\t--color-accent-foreground: ${theme.colors.accentForeground};

\t/* Used for text/icons placed over a darkened image (Hero). */
\t--color-on-image: ${theme.colors.onImage};

\t/* Earth gold for rating stars (Google reviews). */
\t--color-rating: ${theme.colors.rating};

\t/* Radius — sm/md/lg/xl/full. The xl tier (1rem) is the canonical
\t   radius for cards (services, products, reviews, location, hours,
\t   reviews snapshot). The lower tiers exist for smaller surfaces:
\t   buttons (md), badges (md), small chips (sm). */
\t--radius-sm: 0.25rem;
\t--radius-md: 0.5rem;
\t--radius-lg: 0.75rem;
\t--radius-xl: 1rem;
\t--radius-full: 9999px;

\t/* Shadows — light surfaces: slate-tinted lift (readable on rose paper). */
\t--shadow-sm: 0 1px 2px 0 oklch(30% 0.02 270 / 0.08);
\t--shadow-md: 0 6px 18px -4px oklch(25% 0.025 270 / 0.12);
\t--shadow-lg: 0 20px 44px -16px oklch(20% 0.03 270 / 0.16);

\t/* Motion */
\t--duration-fast: ${theme.motion.durationFast};
\t--duration-normal: ${theme.motion.durationNormal};
\t--duration-slow: ${theme.motion.durationSlow};

\t--ease-standard: cubic-bezier(0.4, 0, 0.2, 1);
}
${END_MARKER}`;
}

function readTheme() {
	const source = readFileSync(THEME_PATH, 'utf8');
	const colorsBlock = extractBlock(source, 'colors');
	const motionBlock = extractBlock(source, 'motion');

	return {
		colors: {
			background: pickValue(colorsBlock, 'background'),
			backgroundAlt: pickValue(colorsBlock, 'backgroundAlt'),
			foreground: pickValue(colorsBlock, 'foreground'),
			muted: pickValue(colorsBlock, 'muted'),
			border: pickValue(colorsBlock, 'border'),
			primary: pickValue(colorsBlock, 'primary'),
			primaryForeground: pickValue(colorsBlock, 'primaryForeground'),
			accent: pickValue(colorsBlock, 'accent'),
			accentHover: pickValue(colorsBlock, 'accentHover'),
			accentForeground: pickValue(colorsBlock, 'accentForeground'),
			onImage: pickValue(colorsBlock, 'onImage'),
			rating: pickValue(colorsBlock, 'rating'),
		},
		motion: {
			durationFast: pickValue(motionBlock, 'durationFast'),
			durationNormal: pickValue(motionBlock, 'durationNormal'),
			durationSlow: pickValue(motionBlock, 'durationSlow'),
		},
	};
}

function syncCss() {
	const theme = readTheme();
	const block = generateThemeBlock(theme);

	const css = readFileSync(CSS_PATH, 'utf8');
	const startIdx = css.indexOf(START_MARKER);
	const endIdx = css.indexOf(END_MARKER);

	if (startIdx === -1 || endIdx === -1) {
		throw new Error(
			`sync-theme: markers not found in ${CSS_PATH}. ` +
				`Add ${START_MARKER} … ${END_MARKER} around the @theme block.`,
		);
	}
	if (endIdx < startIdx) {
		throw new Error(
			'sync-theme: END_MARKER appears before START_MARKER in global.css.',
		);
	}

	const before = css.slice(0, startIdx);
	const after = css.slice(endIdx + END_MARKER.length);
	const next = before + block + after;

	if (next === css) {
		console.log('sync-theme: global.css already in sync — no changes.');
		return;
	}

	writeFileSync(CSS_PATH, next, 'utf8');
	console.log(
		'sync-theme: regenerated @theme block in src/styles/global.css ' +
			`from src/config/theme.ts (primary=${theme.colors.primary}).`,
	);
}

try {
	syncCss();
} catch (err) {
	console.error(err.message);
	process.exit(1);
}
